version: "3"

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spidermail
      MYSQL_USER: spidermail
      MYSQL_PASSWORD: spidermail
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
    - "3306:3306"
    networks:
      - app-tier
  app:
    build: .
    environment:
      DB_USER: spidermail
      DB_PASSWORD: spidermail
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: spidermail
    volumes:
      - ".:/go/src"
    ports:
      - "8080:8080"
    tty: true
    links:
      - db
    networks:
      - app-tier
    depends_on:
      - db
  rabbitmq:
    image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
    ports:
      - '15672:15672'
      - "5672:5672"
    volumes:
      - 'rabbitmq_data:/bitnami'
    networks:
      - app-tier
volumes:
  rabbitmq_data:
    driver: local