version: "3"

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spidermail
      MYSQL_USER: spidermail
      MYSQL_PASSWORD: spidermail
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
    - "3306:3306"
  app:
    build: .
    environment:
      DB_USER: spidermail
      DB_PASSWORD: spidermail
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: spidermail
    volumes:
      - ".:/go/src"
    ports:
      - "8080:8080"
    tty: true
    links:
      - db
    depends_on:
      - db

  app-consumer:
    image: golang:1.13-alpine
    ports:
      - '8088:8088'
    volumes:
      - './rabbitmq/:/go/src/github.com/JackMaarek/spiderMail/'
      - './services/MailerService.go:/go/src/github.com/JackMaarek/spiderMail/services/MailerService.go'
      - './models/:/go/src/github.com/JackMaarek/spiderMail/models/'
      - './go.mod:/go/src/github.com/JackMaarek/spiderMail/go.mod'
    command: go run /go/src/github.com/JackMaarek/spiderMail/main.go

  rabbitmq:
    image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
    ports:
      - '15672:15672'
      - "5672:5672"
    volumes:
      - 'rmq_data:/bitnami'
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: bitnami
volumes:
  rmq_data:
    driver: local
